baseURL: "https://boehs.ml/blog"
title: Evan Boehs's Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Evan Boehs
    description: "Oh no..."
    author: Me
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]

    defaultTheme: light # dark, light
    disableThemeToggle: false
    ShowReadingTime: true
    ShowShareButtons: true
    disableSpecial1stPost: false
    comments: true
    hidemeta: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "https://avatars.githubusercontent.com/u/51836263?s=460&u=a7a4e671c9f4db3d06d1f4a7ebd7591c75832d95&v=4"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Home"
        icon: https://avatars.githubusercontent.com/u/51836263?s=460&u=a7a4e671c9f4db3d06d1f4a7ebd7591c75832d95&v=4
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hey hello there \U0001F44B"
        Content: The rantings of a disgruntled programmer

    socialIcons:
        - name: twitter
          url: ""
        - name: website
          url: "https://boehs.ml"
        - name: github
          url: "https://github.com/boehs"
        - name: linkedin
          url: ""
          
    analytics:
        google:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: search
          name: search
          url: /search/
          weight: 30
        - identifier: archive
          name: archive
          url: /archive/
          weight: 40
        - identifier: homepage
          name: homepage
          url: https://boehs.ml
          weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai