[build]
    publish = "dist"
    command = "pnpm run build"
    framework = "#static"
# If skip_processing = true, all other settings are ignored
[dev]
    publish = "dist"
    command = "gulp dev"
    framework = "#static"
[[edge_functions]]
    function = "eleventy-edge"
    path = "/*"
    
#[[redirects]]
#    from = "https://evn.netlify.app/*"
#    to = "https://boehs.org/:splat"
#    status = 301
#    force = "true"
