[build]
    publish = "dist"
    command = "pnpm run build"
# If skip_processing = true, all other settings are ignored
[build.processing]
    skip_processing = false
[build.processing.css]
    bundle = true
    minify = true
[build.processing.js]
    bundle = true
    minify = true
[build.processing.html]
    pretty_urls = true
[build.processing.images]
  compress = true
[[redirects]]
    from = "https://evn.netlify.app/*"
    to = "https://boehs.org/:splat"
    status = 301
    force = "true"
